export interface QuestionCategory {
  id: string;
  label: string;
  /** Tabler icon name (resolved in the UI). */
  icon: string;
  /** Short audience hint. */
  audience: "1P" | "3P" | "Both";
  questions: string[];
}

// The vendor question catalog — every entry is a one-click entry point into the
// Ask an Amazonian chat. Ordered roughly by urgency / value to a 1P vendor.
export const QUESTION_CATEGORIES: QuestionCategory[] = [
  {
    id: "cost-increases",
    label: "Pricing & cost increases",
    icon: "trending-up",
    audience: "1P",
    questions: [
      "How do I get Amazon to approve my wholesale cost increase?",
      "Why are all my cost increase requests automatically rejected?",
      "How often can I request cost increases, and what's the approval timeline?",
      "What's the best way to justify a cost increase to Amazon?",
      "Can I raise prices on other platforms first, then adjust on Amazon?",
      "My input costs have gone up due to tariffs — how do I pass this through to Amazon?",
      "How much margin do I need to request a cost increase?",
      "What's the difference between MSRP and cost price, and why does Amazon ignore my MSRP?",
      "Can I submit a cost increase request if I'm unprofitable right now?",
    ],
  },
  {
    id: "profitability",
    label: "Profitability & margins",
    icon: "report-money",
    audience: "1P",
    questions: [
      "How do I calculate my true contribution profit (CP) on Amazon?",
      "Why is my Amazon profitability lower than expected despite high sales volume?",
      "What's the difference between gross margin and net PPM (pure profit per unit)?",
      "Which of my SKUs are actually profitable on Amazon?",
      "Should I remove low-margin products, or try to improve terms?",
      "What's the 'Fool's Gold ASIN' trap, and how do I avoid it?",
      "How do I know if a product should stay on 1P or move to 3P based on profitability?",
      "Can I get a breakdown of what I'm actually earning per unit after all deductions?",
      "How much annual revenue makes me a 'tier 1' vendor with better support?",
    ],
  },
  {
    id: "chargebacks",
    label: "Chargebacks & shortages",
    icon: "receipt-tax",
    audience: "1P",
    questions: [
      "Why is Amazon charging me for shortage claims when I shipped the correct quantity?",
      "How do I dispute a shortage claim or chargeback?",
      "What documentation do I need to prove what I actually shipped?",
      "Are my chargebacks increasing over time, and what does that mean?",
      "What are the most common reasons for chargebacks?",
      "How do I avoid ASN (Advance Shipment Notice) mismatches?",
      "What labeling mistakes trigger chargebacks, and how do I prevent them?",
      "What's the difference between a chargeback and a deduction?",
      "What's a realistic chargeback rate, and when should I be concerned?",
      "Can I appeal chargebacks after they've been applied?",
    ],
  },
  {
    id: "inventory-po",
    label: "Inventory & purchase orders",
    icon: "truck-delivery",
    audience: "1P",
    questions: [
      "Why does Amazon suddenly stop ordering my product with no explanation?",
      "What does 'CRAP status' (Can't Realize A Profit) mean, and can I get out of it?",
      "How do I forecast Amazon's purchase orders when they're unpredictable?",
      "Why does Amazon over-order sometimes and under-order others?",
      "Can I refuse to fulfill a purchase order if it's too large?",
      "What happens if I don't confirm a PO — will I get penalized?",
      "Why does Amazon stock out of my products when I have inventory available?",
      "What's the best way to manage overstock when Amazon stops ordering?",
    ],
  },
  {
    id: "pricing-control",
    label: "Retail price control",
    icon: "tag",
    audience: "1P",
    questions: [
      "Why can't I control the retail price on Amazon like on other platforms?",
      "Does Amazon violate my MAP (Minimum Advertised Price) policy?",
      "How do Amazon's pricing bots work, and do they match competitors automatically?",
      "What happens if Amazon prices my product below my cost?",
      "Can I stop Amazon from price-matching grey market or unauthorized sellers?",
      "How do I maintain brand positioning if Amazon underprices my products?",
      "Should I launch new products on 3P first to control pricing before moving to 1P?",
    ],
  },
  {
    id: "catalog",
    label: "Product content & catalog",
    icon: "photo-edit",
    audience: "Both",
    questions: [
      "Why can't I edit my product title, description, or images on Vendor Central?",
      "How do I request changes to my product detail page?",
      "Why does Amazon show competitor products at the top of my detail page?",
      "How long does it take Amazon to approve product content changes?",
      "What if Amazon's product description is inaccurate or outdated?",
    ],
  },
  {
    id: "support",
    label: "Support & vendor managers",
    icon: "headset",
    audience: "1P",
    questions: [
      "Do I have a dedicated vendor manager, and how do I contact them?",
      "Why did I lose my vendor manager, and who do I escalate to now?",
      "What's the difference between a Vendor Manager and an Account Vendor Specialist (AVS)?",
      "Is AVS worth paying for, and what does it actually deliver?",
      "How do I get 'tier 1' vendor support status?",
      "Why are my support tickets getting generic, unhelpful responses?",
      "How do I reach my vendor manager for strategic vs. operational issues?",
    ],
  },
  {
    id: "negotiation",
    label: "Negotiations & AVN",
    icon: "writing-sign",
    audience: "1P",
    questions: [
      "What should I prepare for my Annual Vendor Negotiation (AVN)?",
      "How do I propose new terms or discounts to Amazon?",
      "What leverage do I have in negotiations if Amazon controls pricing?",
      "Can I negotiate lower co-op or allowance percentages?",
      "Should I propose cost-savings programs (Direct Import, Vendor Flex, FFP) to improve terms?",
      "How do I frame negotiations around Amazon's profitability goals, not just mine?",
      "Can I renegotiate mid-contract, or do I wait for renewal?",
    ],
  },
  {
    id: "advertising",
    label: "Advertising & marketing",
    icon: "speakerphone",
    audience: "Both",
    questions: [
      "Why pay for Sponsored Ads when I'm already selling to Amazon wholesale?",
      "How do I calculate ROI on Amazon advertising vs. co-op contributions?",
      "Can I reduce my advertising spend and maintain profitability?",
      "Should advertising be part of my contribution margin calculation?",
      "What's the difference between retail media (co-op) and PPC (Sponsored Ads)?",
    ],
  },
  {
    id: "account-status",
    label: "Account status & compliance",
    icon: "shield-check",
    audience: "Both",
    questions: [
      "Why is my account in 'probation' status, and how do I get out?",
      "What compliance issues trigger account suppression or restrictions?",
      "How do I know if my account is at risk of being deactivated?",
      "What's the difference between account suspension and delisting?",
      "What's happening with Amazon reducing vendor relationships — am I next?",
    ],
  },
  {
    id: "model-strategy",
    label: "1P vs 3P vs hybrid",
    icon: "git-branch",
    audience: "Both",
    questions: [
      "Should I sell on Vendor Central (1P) or Seller Central (3P)?",
      "What's the difference between Vendor Central and Seller Central economics?",
      "Can I run a hybrid model with some products on 1P and others on 3P?",
      "If I launch new products on 3P first, will Amazon approach me to buy them 1P?",
      "Should I move underperforming SKUs from 1P to 3P?",
      "What are the risks of running both 1P and 3P accounts simultaneously?",
      "How much 3P volume do I need before Amazon invites me to Vendor Central?",
      "Is it time to leave Vendor Central entirely and focus on 3P?",
      "Can Amazon force me to move from 1P to 3P?",
    ],
  },
  {
    id: "financial-ops",
    label: "Financial & operational",
    icon: "calculator",
    audience: "1P",
    questions: [
      "When does Amazon pay vendors, and why is payment slower than Seller Central?",
      "How do I reconcile my Amazon payments with my actual sales and deductions?",
      "What financial metrics should I track daily vs. monthly vs. quarterly?",
      "How do I set up internal dashboards to monitor net PPM by ASIN?",
      "Should I hire an Amazon consultant or agency to optimize operations?",
    ],
  },
  {
    id: "sku-rationalization",
    label: "SKU rationalization",
    icon: "list-check",
    audience: "Both",
    questions: [
      "Which low-performing SKUs should I discontinue on Amazon?",
      "How do I decide if a 'Fool's Gold ASIN' is worth keeping?",
      "Should I bundle products to create new ASINs and reset pricing?",
      "What's the best way to re-SKU a product to get a better wholesale price?",
      "Can I request that Amazon stop ordering a specific SKU?",
    ],
  },
  {
    id: "getting-started",
    label: "Getting started & setup",
    icon: "rocket",
    audience: "3P",
    questions: [
      "How do I create an Amazon seller account?",
      "What are the professional vs. individual selling plans?",
      "What are the costs of selling on Amazon (referral fees, FBA fees, etc.)?",
      "How do I set up Fulfillment by Amazon (FBA)?",
      "How do I prepare and ship products to Amazon fulfillment centers?",
      "What's an ASN (Advance Shipment Notice) and how do I create one?",
      "How do I register my brand on Amazon Brand Registry?",
    ],
  },
  {
    id: "market-intel",
    label: "Competitive & market data",
    icon: "chart-arcs",
    audience: "Both",
    questions: [
      "How do I see how my products rank against competitors on Amazon?",
      "Can I access competitive pricing data through Amazon?",
      "How do I benchmark my Amazon performance against industry standards?",
      "How does my net PPM compare to other vendors in my category?",
    ],
  },
  {
    id: "reporting",
    label: "Data & reporting",
    icon: "chart-dots",
    audience: "1P",
    questions: [
      "What reports does Vendor Central provide, and are they sufficient?",
      "Does Amazon offer premium analytics packages for vendors?",
      "How do I get sales data broken down by ASIN, region, or time period?",
      "Can I export data from Vendor Central to my own analytics tools?",
      "How often is data updated in Vendor Central?",
    ],
  },
  {
    id: "escalation",
    label: "Process & escalation",
    icon: "arrow-up-circle",
    audience: "1P",
    questions: [
      "What's the correct escalation path for unresolved issues?",
      "How long should I wait for a response to a support ticket?",
      "Can I request a call with Amazon instead of email support?",
      "Who do I contact for strategic account decisions vs. operational problems?",
      "Is there an executive escalation process if standard support fails?",
    ],
  },
];

export const TOTAL_QUESTIONS = QUESTION_CATEGORIES.reduce((n, c) => n + c.questions.length, 0);
